export default {
  creation_date: '2018-05-22T15:49:52.419437Z',
  modification_date: '2018-05-22T15:49:52.419481Z',
  type: 'fs',
  authors: 'FNNDSC (dev@babyMRI.org)',
  title: 'Mock plugin',
  category: '',
  description: 'A mocked plugin for testing',
  documentation: 'http://wiki',
  license: 'Opensource (MIT)',
  version: '0.1',
  execshell: 'python3',
  selfpath: '/usr/src/simplefsapp',
  selfexec: 'simplefsapp.py',
  min_number_of_workers: 1,
  max_number_of_workers: 1,
  min_cpu_limit: 1000,
  max_cpu_limit: 2147483647,
  min_memory_limit: 200,
  max_memory_limit: 2147483647,
  min_gpu_limit: 0,
  max_gpu_limit: 0,
  parameters: [
    {
      name: 'dir',
      type: 'path',
      optional: true,
      default: './',
      flag: '--dir',
      action: 'store',
      help: 'look up directory',
    },
  ],
  items: [{
    data: [{
      name: 'id',
      value: 0,
    }],
  }],
};
